name: frontend
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install
        run: npm install
        working-directory: ./app
      - name: Check
        run: npm run lint
        working-directory: ./app
